sudo: false
language: node_js
node_js:
  - node
  - lts/*

cache:
  directories:
    - "node_modules"

install:
  - yarn install

script:
  - yarn lint
  - yarn test

after_script:
  - node createjson.js
  - yarn build

deploy:
 - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: $AWS_DEFAULT_REGION
    bucket: codelabs.eleven-labs.com
    local_dir: _posts
    skip_cleanup: true
    on:
        branch: master

after_deploy:
  - node index_algolia.js
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_DISTRIBUTION_ID" --paths "/*"

notifications:
  slack:
    rooms:
      - secure: RMLFfJF2I3ZqzDgKkqwaFsrLmBcnQWABgAgkNWLZGym/2GsKQUaT4tD+vcvwxGRra9mhg7P/2dSF285rpWsMo7Hyi+Hq1qWYlgkM7Bz2oHHng/FNr0YVEVoZ+ezKZVlT8myaGQgrnLocJn0uPVV6GBK8l0txYmRBtBXP0DPnJLgII4FPQ4zXc710ofSFJ+ozLnZ+09OJZw+939O8hpVtAld7nbMortf+MKpvXOCJqycbFOncb0uPPE2MgOkxKmNZRmXrX/wFTxpotY1xQdKgUZrNpPGrRjrIMm8ZHGI/atoojG0PCY1jCYk+6RQVIdLAnBAZIiNbyzoogkTzHSJIBgkh/DTTMnVNYQ8ZPvO2sI0qlcSlcsFIX3Y9kh39CszsQslXs0AzAXbQMkoH8aWy9wm1tno1EiAP01DqWgXJhN2aYpxYISkEOI/5yVjQE2Ggm1LgFzHrdWWy4R27xdr0w+9+805KBeOp6yMPsJxM08nXA77CESDSCkNvediti6n9hWpIPBFwlB5C90S6WOHM2vPevSGHooMEjosGi6Rycg/D+/aecJEi4MhkfNY8VO7E1uyjkfi9URmouNZOE2rRTX7gjK2AZxz72pIOKtJc4yeB7dVdpzqTgFXi7PTtq4fxMFykWKIi2dbcUrcs2XTzhWqAmQKLWirmPrI0psCgWrU=
    template:
      - "Nouvelle version de codelabs en prod => %{message}"
    on_pull_requests: false
    on_success: always
    on_failure: never
    on:
      branch: master